version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: actor-sites-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: actor_admin
      POSTGRES_PASSWORD: actor_password_dev
      POSTGRES_DB: actor_sites_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - actor-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U actor_admin -d actor_sites_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: actor-sites-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - actor-network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  actor-network:
    driver: bridge
